/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.graphicInterface.view;
import com.javaProject.clases.*;

/**
 *
 * @author juann
 */
public class AddRandomNumbersView extends javax.swing.JPanel {
    AddRandomNumbers addRandomNumbers = new AddRandomNumbers();
    /**
     * Creates new form LeapYearView
     */
    public AddRandomNumbersView() {
        initComponents();
        this.viewInfo();
    }
    public void viewInfo(){
        String infoReturn = addRandomNumbers.printValues();
        info.setText(infoReturn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        info = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        consult = new javax.swing.JButton();
        result = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(400, 421));
        setPreferredSize(new java.awt.Dimension(400, 421));

        info.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        info.setForeground(new java.awt.Color(51, 51, 51));

        input.setBackground(new java.awt.Color(102, 102, 102));
        input.setForeground(new java.awt.Color(255, 255, 255));

        consult.setForeground(new java.awt.Color(51, 51, 51));
        consult.setText("Sumar ➕");
        consult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultMouseClicked(evt);
            }
        });

        result.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consult, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(info)
                .addGap(37, 37, 37)
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void consultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultMouseClicked
       String text = input.getText();
       int cant = Integer.parseInt(text);
       addRandomNumbers.setResponseUser(cant);
       String valuReturn = addRandomNumbers.validateAdd();
       result.setText(valuReturn);
    }//GEN-LAST:event_consultMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consult;
    private javax.swing.JLabel info;
    private javax.swing.JTextField input;
    private javax.swing.JLabel result;
    // End of variables declaration//GEN-END:variables
}
