/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.grapicInterface.view;
import com.javaProject.clases.*;

/**
 *
 * @author juann
 */
public class RockPaperScissorsView extends javax.swing.JPanel {
    
     private int option;
    
    /**
     * Creates new form LeapYearView
     */
    public RockPaperScissorsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        result = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paper = new javax.swing.JButton();
        rock = new javax.swing.JButton();
        scissors = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(355, 344));
        setMinimumSize(new java.awt.Dimension(355, 344));
        setPreferredSize(new java.awt.Dimension(355, 344));

        result.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Piedra, papel o tijera");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Elija una opción");

        paper.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        paper.setForeground(new java.awt.Color(51, 51, 51));
        paper.setText("Papel ✋");
        paper.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperActionPerformed(evt);
            }
        });

        rock.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rock.setForeground(new java.awt.Color(51, 51, 51));
        rock.setText("Piedra ✊");
        rock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rockMouseClicked(evt);
            }
        });

        scissors.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        scissors.setForeground(new java.awt.Color(51, 51, 51));
        scissors.setText("Tijeras ✂️");
        scissors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        scissors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scissorsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rock, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paper, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scissors, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void playGame(){
        RockPaperScissors rockPaperScissors = new RockPaperScissors(this.option);
        String resultPlay = rockPaperScissors.play();
        result.setText(resultPlay);
    }
    
    private void paperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperActionPerformed
        // TODO add your handling code here:
        this.option = 2;
        playGame();
    }//GEN-LAST:event_paperActionPerformed

    private void rockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rockMouseClicked
        this.option = 1; 
        playGame();
    }//GEN-LAST:event_rockMouseClicked

    private void scissorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scissorsMouseClicked
        this.option = 3;
        playGame();
    }//GEN-LAST:event_scissorsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton paper;
    private javax.swing.JLabel result;
    private javax.swing.JButton rock;
    private javax.swing.JButton scissors;
    // End of variables declaration//GEN-END:variables
}
